// resources/js/Components/Footer.vue
<template>
  <footer class="bg-gray-800 border-t border-gray-700 py-8">
    <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
      <div class="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent mb-4">
        Gabriel Gonçalves
      </div>
      <p class="text-gray-400 mb-6">
        Desenvolvedor em ascensão • Análise e Desenvolvimento de Sistemas • Fatec Ourinhos
      </p>
      
      <!-- Links Sociais com design melhorado -->
      <div class="flex justify-center space-x-6 mb-6">
        <a 
          href="https://linkedin.com/in/gabriel-gonçalves-554a41311" 
          target="_blank"
          rel="noopener noreferrer"
          class="group flex items-center justify-center w-12 h-12 bg-gray-700 rounded-full hover:bg-blue-600 transition-all duration-300 hover:scale-110 hover:shadow-lg hover:shadow-blue-500/25"
          title="LinkedIn"
        >
          <svg class="w-6 h-6 text-gray-300 group-hover:text-white transition-colors" fill="currentColor" viewBox="0 0 24 24">
            <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
          </svg>
        </a>
        
        <a 
          href="https://github.com/GabrielG71" 
          target="_blank"
          rel="noopener noreferrer"
          class="group flex items-center justify-center w-12 h-12 bg-gray-700 rounded-full hover:bg-purple-600 transition-all duration-300 hover:scale-110 hover:shadow-lg hover:shadow-purple-500/25"
          title="GitHub"
        >
          <svg class="w-6 h-6 text-gray-300 group-hover:text-white transition-colors" fill="currentColor" viewBox="0 0 24 24">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
          </svg>
        </a>
      </div>
      
      <div class="mt-6 pt-6 border-t border-gray-700">
        <p class="text-gray-500 text-sm">
          © 2025 Gabriel Gonçalves. Todos os direitos reservados.
        </p>
      </div>
    </div>
  </footer>
</template>

// src/components/LayoutComponents/Footer.tsx
import { FaLinkedin, FaGithub, FaWhatsapp } from "react-icons/fa";

export default function Footer() {
  return (
    <footer className="bg-[#0e1117] text-gray-400 pt-16 pb-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center space-y-8">
          <div className="space-y-4">
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 text-transparent bg-clip-text hover:scale-105 transition-transform duration-300">
              Gabriel Gonçalves
            </h2>

            <p className="text-lg sm:text-xl text-gray-300 max-w-2xl mx-auto leading-relaxed">
              Desenvolvedor FullStack • Análise e Desenvolvimento de Sistemas •
              Fatec Ourinhos
            </p>
          </div>

          <div className="flex justify-center space-x-6 sm:space-x-8">
            <a
              href="https://www.linkedin.com/in/gabriel-gonçalves-554a41311/"
              target="_blank"
              rel="noopener noreferrer"
              className="group bg-gray-700/30 p-4 sm:p-5 rounded-2xl hover:bg-blue-500/20 transition-all duration-300 hover:scale-110 hover:shadow-lg hover:shadow-blue-500/25"
            >
              <FaLinkedin className="text-white text-2xl sm:text-3xl group-hover:text-blue-400 transition-colors duration-300" />
            </a>
            <a
              href="https://github.com/GabrielG71"
              target="_blank"
              rel="noopener noreferrer"
              className="group bg-gray-700/30 p-4 sm:p-5 rounded-2xl hover:bg-gray-500/20 transition-all duration-300 hover:scale-110 hover:shadow-lg hover:shadow-gray-500/25"
            >
              <FaGithub className="text-white text-2xl sm:text-3xl group-hover:text-gray-300 transition-colors duration-300" />
            </a>
            <a
              href="https://wa.me/5518998005937"
              target="_blank"
              rel="noopener noreferrer"
              className="group bg-gray-700/30 p-4 sm:p-5 rounded-2xl hover:bg-green-500/20 transition-all duration-300 hover:scale-110 hover:shadow-lg hover:shadow-green-500/25"
            >
              <FaWhatsapp className="text-white text-2xl sm:text-3xl group-hover:text-green-400 transition-colors duration-300" />
            </a>
          </div>

          <div className="relative">
            <hr className="border-t border-gray-700 mx-auto w-full max-w-md" />
            <div className="absolute inset-0 flex justify-center">
              <div className="bg-[#0e1117] px-4">
                <div className="w-2 h-2 bg-gradient-to-r from-blue-400 to-purple-500 rounded-full"></div>
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-sm sm:text-base text-gray-500">
              © {new Date().getFullYear()} Gabriel Gonçalves. Todos os direitos
              reservados.
            </p>
            <p className="text-xs sm:text-sm text-gray-600">
              Desenvolvido com ❤️ usando Next.js e Tailwind CSS
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
}
